apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rankings
  name: rankings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rankings
  template:
    metadata:
      labels:
        app: rankings
    spec:
      containers:
      - image: rankingsapp:latest
        name: rankingsapp
        volumeMounts: 
        - mountPath: "/root/.aspnet/DataProtection-Keys"
          name: rankings-volume
        imagePullPolicy: Never
        env:
        - name: ConnectionStrings__RankingsContext
          value: {{ .Values.connectionString }}
      volumes:
      - name: rankings-volume
        persistentVolumeClaim:
          claimName: rankings-pvc
